server:
  port: 9526

spring:
  application:
    name: cloud-gateway

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: path_routh1
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**
            - After=2024-07-25T16:23:30.729676800+08:00[Asia/Shanghai]
#            - Before=2024-07-25T16:24:10.729676800+08:00[Asia/Shanghai]
#            - Between=2024-07-25T16:23:30.729676800+08:00[Asia/Shanghai],2024-07-25T16:28:20.729676800+08:00[Asia/Shanghai]
#            - Cookie=username,yzywx           #携带cookie并且username=yzywx
#            - Header=WXYZYI, \d+              #请求头是WXYZYI,并且值为正数
#            - Host=**.wxiyzy.com              #主机携带必要信息
#            - Query=username, \d+             #要有参数名username,并且值为正数
#            - Method=POST,GET                 #请求方法必须为POST

        - id: path_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**

#        - id: pay_routh3 #pay_routh3
#          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
#          predicates:
#            - Path=/pay/gateway/filter/**                # 断言，路径相匹配的进行路由
#          filters:
#            - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
#            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
